config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get 'statics/privacy', to: 'statics#privacy'
  get 'statics/support', to: 'statics#support'
  get 'statics/support', to: 'statics#support'
  get 'statics/overview', to: 'statics#overview'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :users, only: [:show, :index]
  namespace :admin do
    resources :users, only: [:edit, :update]
  end
  resources :collected_shifts, except: [:show, :new] do
    resources :created_shifts, only: [:create, :destroy], module: 'admin'
  end
  resources :created_shifts, only: [:index], module: 'admin'
  resources :attendances, except: [:show]
  resources :companies, except: [:index, :destroy] do
    member do
      post :regenerate
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(facebook google_oauth2)
  has_many :collected_shifts, dependent: :destroy
  has_many :created_shifts, through: :collected_shifts
  has_many :attendances, dependent: :destroy
  belongs_to :company, optional: true

  validates :name, presence: true
  validate :min_base_salary

  scope :colleagues, -> (user) { where(company_id: user.company_id) }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def attendances_on_term(month)
    Attendance.on_term(month).where(user: self)
  end

  def attendances_in_this_month
    Attendance.in_this_month.where(user: self)
  end

  def calc_total_wage(term)
    total_hours = attendances_on_term(term).calc_total_hours
    str = total_hours.match(/(.*):(.*)/)
    total_wage = (str[1].to_i + str[2].to_f / 60) * base_salary
    total_wage.floor
  end

  def update_with_authentication(resource, params)
    company = Company.find_by(name: params[:company])
    if company && company.auth_token == params[:company_auth_token]
      resource.update(company: company)
    else
      errors.add(:company, '情報が正しくありません')
      false
    end
  end

  private

  def min_base_salary
    if base_salary < 790
      errors.add(:base_salary, 'が低すぎます')
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :admin_user

    def edit
      @user = User.find(params[:id])
    end

    def update
      user = User.find(params[:id])
      if user.update(user_params)
        redirect_to users_path, flash: { success: 'ユーザー情報を更新しました' }
      else
        render 'edit'
      end
    end

    private

    def user_params
      params.require(:user).permit(:admin, :base_salary)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env['omniauth.auth'].except(:extra))
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      flash[:danger] = "#{provider}アカウントによる認証に失敗しました"
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    if params[:path]
      render "users/registrations/#{params[:path]}"
    end
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      redirect_to user_path(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      if params[:path]
        render "users/registrations/#{params[:path]}"
      else
        respond_with resource
      end
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    if params[:company].present? || params[:company_auth_token].present?
      resource.update_with_authentication(resource, params)
    else
      resource.update_with_password(params)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:show]
  before_action :check_company, only: [:index]

  def show
    @user = User.find(params[:id])
    @collected_shift = current_user.collected_shifts.build
    @collected_shifts = CollectedShift.where(user: current_user)
    @attendance = current_user.attendances.build
    @attendances = Attendance.where(user: current_user).in_this_month.recent
  end

  def index
    @users = User.colleagues(current_user)
  end

  private

  def correct_user
    unless User.find(params[:id]) == current_user
      redirect_to users_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/index.html.erb
<div class="wrapper">
  <div class="col-md-8 col-md-offset-1 all-staffs-table">
    <h2>スタッフ一覧</h2>
    <% if current_user.admin? %>
      <table>
        <tr>
          <th>スタッフ名</th>
          <th>区分</th>
          <th>アドレス</th>
          <th>基本給</th>
          <th>今月の実績</th>
        </tr>
        <% @users.each do |user| %>
          <tr class="staff-profile">
            <td><%= user.name %></td>
            <td><%= link_to user.admin? ? '管理者' : '一般ユーザー', edit_admin_user_path(user) %></td>
            <td><%= user.email %></td>
            <td><%= user.base_salary %> /h</td>
            <td><%= user.attendances_in_this_month.size %> 日</td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <div class="staff-lists">
        <% @users.each do |user| %>
          <li>
            <%= gravatar_for(user) %>
            <p><strong><%= user.name %></strong></p>
          </li>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% if current_user.admin? %>
  <div class="row">
    <div class="col-md-offset-3 col-md-8 explanation">
      <p><strong>ユーザー区分</strong>の更新および、<strong>基本給</strong>の更新は区分リンクから行ってください。</p>
      <p>スタッフ名リンクより、スタッフページに移動できます。スタッフの<strong>シフト提出状況・勤怠詳細</strong>が確認できます。</p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="wrapper right-side-wrapper">
  <div class="row">
    <div class="col-md-2 sidebar left-sidebar">
      <li><%= link_to 'アカウント設定', edit_user_registration_path %></li>
      <li><%= link_to 'パスワードの変更', edit_user_registration_path(path: 'edit_password') %></li>
      <% if current_user.company %>
        <li><button id="attendance-open-modal" class="btn btn-default">勤怠を入力する</button></li>
        <li><button id="collected-shift-open-modal" class="btn btn-default">シフト新規作成</button></li>
        <!-- モーダルエリア -->
        <div id="collected-shift-modal-area">
          <%= render 'shared/modal', resource: @collected_shift %>
        </div>
        <div id="attendance-modal-area">
          <%= render 'shared/modal', resource: @attendance %>
        </div>
        <!-- 勤怠 -->
        <div class="user-attendance">
          <h4>勤怠</h4>
          <% if @attendances.present? %>
            <ul>
              <% @attendances.each do |attendance| %>
                <%= link_to(edit_attendance_path(attendance), class: 'attendance-list') do %>
                  <li><%= l attendance.started_at, format: :full %> → <%= l attendance.finished_at, format: :default %></li>
                <% end %>
              <% end %>
            </ul>
          <% else %>
            <ul>
              <h4>未登録</h4>
            </ul>
          <% end %>
        </div>
      <% else %>
        <li><%= link_to '所属を登録する', edit_user_registration_path(path: 'edit_company') %></li>
      <% end %>
    </div>
    <!-- テーブルエリア -->
    <div class="col-md-6 col-md-offset-1 table-area">
      <h2>提出済みシフト</h2>
      <%= month_calendar events: @collected_shifts do |date, shifts| %>
        <%= date %>
        <% shifts.each do |shift| %>
          <div>
            <%= link_to edit_collected_shift_path(shift) do %>
              <%= l shift.started_at %> -
              <%= l shift.finished_at %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>