config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get 'statics/privacy', to: 'statics#privacy'
  get 'statics/support', to: 'statics#support'
  get 'statics/support', to: 'statics#support'
  get 'statics/overview', to: 'statics#overview'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :users, only: [:show, :index]
  namespace :admin do
    resources :users, only: [:edit, :update]
  end
  resources :collected_shifts, except: [:show, :new] do
    resources :created_shifts, only: [:create, :destroy], module: 'admin'
  end
  resources :created_shifts, only: [:index], module: 'admin'
  resources :attendances, except: [:show]
  resources :companies, except: [:index, :destroy] do
    member do
      post :regenerate
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <% resource.errors.full_messages.each do |message| %>
      <%= message %></br>
    <% end %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="wrapper right-side-wrapper">
  <div class="col-md-5 col-md-offset-2">
    <h2><%= title %></h2>
    <%= form_with(model: resource, local: true) do |f| %>

      <div class="field form-group">
        <%= f.label :started_at, class: 'form-group' %>
        <%= f.datetime_field :started_at, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :finished_at, class: 'form-group' %>
        <%= f.datetime_field :finished_at, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "#{btn}", class: 'form-control light' %>
      </div>
    <% end %>
    <% if defined? delete_link %>
      <%= link_to '削除する', resource, method: :delete, data: { confirm: '削除してよろしいですか' } %>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal-bg"></div>
<div class="modal-wrapper">
  <div id="modal-content">
    <%= form_with(model: resource, local: true) do |f| %>  
      <div class="field form-group">
        <%= f.label :started_at, class: 'form-group' %>
        <%= f.datetime_field :started_at, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :finished_at, class: 'form-group' %>
        <%= f.datetime_field :finished_at, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit '提出', class: 'form-control light' %>
      </div>
    <% end %>
  </div>    
</div>

app/views/shared/_omniauth.html.erb
<div class="oauth-form">
  <p><%= link_to content_tag(:i, '', class: 'fab fa-facebook-square fa-lg icon') + 'Facebookで続行', user_facebook_omniauth_authorize_path, class: 'form-control btn facebook' %></p>
  <p><%= link_to content_tag(:i, '', class: 'fab fa-google fa-lg icon') + 'Googleで続行', user_google_oauth2_omniauth_authorize_path, class: 'form-control btn google' %></p>
</div>

app/views/shared/_sidebar.html.erb
<div class="col-md-2 sidebar">
  <% if user_signed_in? %>
  <li><%= link_to current_user.name, current_user %></li>
    <% if current_user.admin? %>
      <li><%= link_to content_tag(:i, '', class: 'fas fa-building fa-fw fa-lg') + " 会社：#{current_user.company.name}", company_path(current_user.company) %></li>
      <li><%= link_to content_tag(:i, '', class: 'fas fa-user-circle fa-fw fa-lg') + ' スタッフ一覧', users_path %></li>
      <li><%= link_to content_tag(:i, '', class: 'far fa-calendar-alt fa-fw fa-lg') + ' スタッフシフト一覧', collected_shifts_path %></li>
      <li><%= link_to content_tag(:i, '', class: 'far fa-calendar-alt fa-fw fa-lg') + ' 確定済みシフト', created_shifts_path %></li>
      <li><%= link_to content_tag(:i, '', class: 'fas fa-yen-sign fa-fw fa-lg') + ' 勤務実績', attendances_path %></li>
    <% elsif current_user.company %>
      <li><%= link_to content_tag(:i, '', class: 'fas fa-user-circle fa-fw fa-lg') + ' スタッフ一覧', users_path %></li>
      <li><%= link_to content_tag(:i, '', class: 'far fa-calendar-alt fa-fw fa-lg') + ' スタッフシフト一覧', collected_shifts_path %></li>
      <li><a><%= content_tag(:i, '', class: 'fas fa-building fa-fw fa-lg') + " 会社：#{current_user.company.name}" %></a></li>
    <% else %>
      <li><%= link_to content_tag(:i, '', class: 'fas fa-building fa-fw fa-lg') + ' 会社：未登録', edit_user_registration_path(path: 'edit_company') %></li>
    <% end %>
  <% end %>
  <ul>
    <li><%= link_to '概要', statics_overview_path %></li>
    <li><%= link_to 'プライバシー', statics_privacy_path %></li>
    <li><%= link_to 'サポート', statics_support_path %></li>
  </ul>
</div>