config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get 'statics/privacy', to: 'statics#privacy'
  get 'statics/support', to: 'statics#support'
  get 'statics/support', to: 'statics#support'
  get 'statics/overview', to: 'statics#overview'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :users, only: [:show, :index]
  namespace :admin do
    resources :users, only: [:edit, :update]
  end
  resources :collected_shifts, except: [:show, :new] do
    resources :created_shifts, only: [:create, :destroy], module: 'admin'
  end
  resources :created_shifts, only: [:index], module: 'admin'
  resources :attendances, except: [:show]
  resources :companies, except: [:index, :destroy] do
    member do
      post :regenerate
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_secure_token :auth_token
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :admin_user, only: [:show, :edit, :update, :regenerate]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :check_company, only: [:new, :create]

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = current_user.build_company
  end

  def create
    @company = current_user.build_company(company_params)
    if @company.save
      current_user.update(admin: true)
      redirect_to current_user, flash: {
        success: '会社を新規登録しました。認証キーを従業員に配布してください',
        info: "認証キーは `#{@company.auth_token}` です。会社情報より確認できます",
      }
    else
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    company = Company.find(params[:id])
    if company.update(company_params_without_name)
      redirect_to company, flash: { success: '会社情報を更新しました' }
    else
      render 'edit'
    end
  end

  def regenerate
    company = Company.find(params[:id])
    company.regenerate_auth_token
    redirect_to company, flash: { success: '認証キーを再生性しました' }
  end

  private

  def company_params
    params.require(:company).permit(:name, :address, :tel)
  end

  def company_params_without_name
    params.require(:company).permit(:address, :tel)
  end

  def check_company
    if current_user.company
      redirect_to current_user, flash: { danger: '既に会社情報は登録済みです' }
    end
  end

  def correct_user
    company = Company.find(params[:id])
    if company.nil? || (company != current_user.company)
      redirect_to root_url
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<div class="wrapper right-side-wrapper">
  <div class="col-md-5 col-md-offset-2">
    <h2>所属会社を更新</h2>
    <%= form_with(model: @company, local: true) do |f| %>

      <div class="field form-group">
        <%= f.label :name, '会社名', class: 'form-group' %>
        <%= f.text_field :name, required: true, class: 'form-control', readonly: true %>
      </div>

      <div class="field form-group">
        <%= f.label :address, '住所', class: 'form-group' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :tel, '代表番号', class: 'form-group' %>
        <%= f.text_field :tel, class: 'form-control' %>
      </div>
      
      <div class="actions">
        <%= f.submit '更新する', class: 'form-control light' %>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/new.html.erb
<div class="wrapper right-side-wrapper">
  <div class="col-md-5 col-md-offset-2">
    <h2>所属会社を新規登録</h2>
    <%= form_with(model: @company, local: true) do |f| %>

      <div class="field form-group">
        <%= f.label :name, '会社名', class: 'form-group' %>
        <%= f.text_field :name, required: true, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :address, '住所', class: 'form-group' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :tel, '代表番号', class: 'form-group' %>
        <%= f.text_field :tel, class: 'form-control' %>
      </div>
      
      <div class="actions">
        <%= f.submit '登録する', class: 'form-control light' %>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="row wrapper">
  <div class="col-md-8 col-md-offset-1 all-staffs-table">
    <h2>会社情報</h2>
    <table>
      <tr>
        <th>会社名</th>
        <th>住所</th>
        <th>電話番号</th>
        <th>認証キー</th>
        <th></th>
      </tr>
      <tr>
        <td><%= link_to @company.name, edit_company_path(@company) %></td>
        <td><%= @company.address %></td>
        <td><%= @company.tel %></td>
        <td><%= @company.auth_token %></td>
        <td><%= button_to 'トークン再生性', regenerate_company_path(@company), data: { confirm: 'トークンを再生性してよろしいですか?' }, class: 'btn btn-default' %></td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-3 col-md-8 explanation">
    <p><strong>認証キー</strong>を従業員に配布して、各従業員が会社登録を行ってください。</p>
    <% if @company.updated_at < Time.current - 3.months %>
      <span class="alert-danger expire">最後に認証キーを設定してから3ヶ月以上経過しています。再生性をお勧めします。</span>
    <% else %>
      <p>定期的に認証キーを再生性することをお勧めします。</p>
    <% end %>
  </div>
</div>